name: Build and Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo registy
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registy-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        name: show rustfmt version
        with:
          command: fmt
          args: --version
      - uses: actions-rs/cargo@v1
        name: run rustfmt check
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: show clippy version
        with:
          command: clippy
          args: --version
      - uses: actions-rs/cargo@v1
        name: run clippy check
        with:
          command: clippy
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
        continue-on-error: ${{ matrix.rust == 'nightly' }}

  create-release:
    name: Create Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish_crate:
    name: publish_crate
    if: github.event_name == 'push'
    needs: [test, create-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        name: publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          command: publish
